# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone https://github.com/Microsoft/vcpkg
    .\vcpkg\bootstrap-vcpkg.bat
  displayName: Bootstrap vcpkg
- script: .\vcpkg\vcpkg.exe install protobuf:x86-windows protobuf:x64-windows
  displayName: vcpkg install dependencies
- script: mkdir libminiprotoc\build
  displayName: Make Build Directory
- task: CMake@1
  inputs:
    workingDirectory: 'libminiprotoc/build'
    cmakeArgs: '.. -DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake'
